### ISSUE TITLE
any ui ux change which could make the website more aesthetic is acceptable

### ISSUE THREAD

**Issue by aryan-basu** [aryan-basu/pclubstatic#2]

**Comment by kamaljeetsahoo-dev** [comment]
Can I work on this?... I was thinking of improving the alignment a bit, changing the color of Particlejs(particles and strokes) to green and using a more aesthetic design for navbar

**Comment by aryan-basu** [comment]
ya u can idk my project is yet registered or not for hackoctober but also
it would be acceptable only if it suits our pclub team like i have no idea
like what you will be going to do but if it looks good to us we will merged
it
